<?php

namespace App\Support;

class RbacPermissionMatrix
{
    public static function moduleLabels(): array
    {
        return [
            'auth' => 'Auth',
            'order' => 'Order',
            'payment' => 'Payment',
            'kitchen' => 'Kitchen',
            'table' => 'Meja',
            'reservation' => 'Reservasi',
            'product' => 'Produk',
            'stock' => 'Stok',
            'raw_material' => 'Bahan Baku',
            'customer' => 'Customer',
            'membership' => 'Membership',
            'loyalty' => 'Loyalty',
            'kasbon' => 'Kasbon',
            'cicilan' => 'Cicilan',
            'po' => 'PO / DP',
            'promo' => 'Promo',
            'shift' => 'Shift',
            'attendance' => 'Absensi',
            'employee' => 'Karyawan',
            'schedule' => 'Jadwal',
            'approval' => 'Approval',
            'report' => 'Laporan',
            'outlet' => 'Outlet',
            'rbac' => 'RBAC',
            'payment_gateway' => 'Payment Gateway',
            'integration' => 'Integrasi',
            'notification' => 'Notifikasi',
            'printer' => 'Printer',
        ];
    }

    public static function roleTypeLabels(): array
    {
        return [
            'owner' => 'Owner',
            'supervisor' => 'Supervisor',
            'kasir' => 'Kasir',
            'bar' => 'Bar',
            'kitchen' => 'Kitchen',
        ];
    }

    public static function creatableRoleTypes(): array
    {
        return ['supervisor', 'kasir', 'bar', 'kitchen'];
    }

    public static function defaultRoleName(string $type): string
    {
        return self::roleTypeLabels()[$type] ?? ucfirst($type);
    }

    public static function permissionCatalog(): array
    {
        return [
            ['module' => 'auth', 'action' => 'login', 'description' => 'Login ke sistem'],
            ['module' => 'auth', 'action' => 'logout', 'description' => 'Logout'],
            ['module' => 'order', 'action' => 'read', 'description' => 'Lihat daftar & detail order'],
            ['module' => 'order', 'action' => 'create', 'description' => 'Buat order baru'],
            ['module' => 'order', 'action' => 'update', 'description' => 'Edit order (item, catatan)'],
            ['module' => 'order', 'action' => 'cancel', 'description' => 'Batalkan order'],
            ['module' => 'order', 'action' => 'update_status', 'description' => 'Update status order'],
            ['module' => 'order', 'action' => 'approve_edit', 'description' => 'Approve edit pesanan dari customer'],
            ['module' => 'order', 'action' => 'split_bill', 'description' => 'Split / gabung bill'],
            ['module' => 'order', 'action' => 'void', 'description' => 'Void transaksi (butuh approval)'],
            ['module' => 'payment', 'action' => 'create', 'description' => 'Proses pembayaran'],
            ['module' => 'payment', 'action' => 'read', 'description' => 'Lihat riwayat pembayaran'],
            ['module' => 'payment', 'action' => 'refund', 'description' => 'Refund pembayaran (butuh approval)'],
            ['module' => 'payment', 'action' => 'void', 'description' => 'Void pembayaran (butuh approval)'],
            ['module' => 'kitchen', 'action' => 'read', 'description' => 'Lihat antrian kitchen display'],
            ['module' => 'kitchen', 'action' => 'update_status', 'description' => 'Update status masak'],
            ['module' => 'kitchen', 'action' => 'approve', 'description' => 'Approve order selesai (Bar role)'],
            ['module' => 'table', 'action' => 'read', 'description' => 'Lihat layout & status meja'],
            ['module' => 'table', 'action' => 'manage', 'description' => 'Tambah/edit/hapus meja'],
            ['module' => 'table', 'action' => 'qr_generate', 'description' => 'Generate QR code meja'],
            ['module' => 'reservation', 'action' => 'read', 'description' => 'Lihat reservasi'],
            ['module' => 'reservation', 'action' => 'create', 'description' => 'Buat reservasi'],
            ['module' => 'reservation', 'action' => 'update', 'description' => 'Update reservasi'],
            ['module' => 'reservation', 'action' => 'cancel', 'description' => 'Batalkan reservasi'],
            ['module' => 'product', 'action' => 'read', 'description' => 'Lihat katalog produk'],
            ['module' => 'product', 'action' => 'create', 'description' => 'Tambah produk'],
            ['module' => 'product', 'action' => 'update', 'description' => 'Edit produk'],
            ['module' => 'product', 'action' => 'delete', 'description' => 'Nonaktifkan produk'],
            ['module' => 'product', 'action' => 'toggle_availability', 'description' => 'Toggle produk tersedia/tidak'],
            ['module' => 'stock', 'action' => 'read', 'description' => 'Lihat stok'],
            ['module' => 'stock', 'action' => 'add', 'description' => 'Tambah stok masuk'],
            ['module' => 'stock', 'action' => 'adjust', 'description' => 'Adjustment stok manual'],
            ['module' => 'stock', 'action' => 'write_off', 'description' => 'Write-off stok expired/rusak'],
            ['module' => 'raw_material', 'action' => 'read', 'description' => 'Lihat bahan baku'],
            ['module' => 'raw_material', 'action' => 'manage', 'description' => 'Kelola bahan baku'],
            ['module' => 'customer', 'action' => 'read', 'description' => 'Lihat customer database'],
            ['module' => 'customer', 'action' => 'create', 'description' => 'Tambah customer'],
            ['module' => 'customer', 'action' => 'update', 'description' => 'Edit data customer'],
            ['module' => 'membership', 'action' => 'read', 'description' => 'Lihat data membership'],
            ['module' => 'membership', 'action' => 'register', 'description' => 'Daftarkan customer jadi member'],
            ['module' => 'membership', 'action' => 'manage', 'description' => 'Kelola tier & konfigurasi loyalty'],
            ['module' => 'loyalty', 'action' => 'redeem', 'description' => 'Proses redeem poin'],
            ['module' => 'loyalty', 'action' => 'adjust', 'description' => 'Adjustment poin manual'],
            ['module' => 'kasbon', 'action' => 'read', 'description' => 'Lihat kasbon'],
            ['module' => 'kasbon', 'action' => 'create', 'description' => 'Buat kasbon baru'],
            ['module' => 'kasbon', 'action' => 'pay', 'description' => 'Terima pembayaran kasbon'],
            ['module' => 'kasbon', 'action' => 'write_off', 'description' => 'Write-off kasbon'],
            ['module' => 'cicilan', 'action' => 'manage', 'description' => 'Kelola jadwal cicilan'],
            ['module' => 'po', 'action' => 'read', 'description' => 'Lihat PO/DP'],
            ['module' => 'po', 'action' => 'create', 'description' => 'Buat PO/DP'],
            ['module' => 'po', 'action' => 'pay', 'description' => 'Proses pembayaran PO/DP'],
            ['module' => 'po', 'action' => 'cancel', 'description' => 'Batalkan PO/DP'],
            ['module' => 'promo', 'action' => 'read', 'description' => 'Lihat daftar promo'],
            ['module' => 'promo', 'action' => 'create', 'description' => 'Buat promo baru'],
            ['module' => 'promo', 'action' => 'update', 'description' => 'Edit promo'],
            ['module' => 'promo', 'action' => 'toggle', 'description' => 'Aktifkan/nonaktifkan promo'],
            ['module' => 'promo', 'action' => 'apply', 'description' => 'Apply promo/voucher ke order'],
            ['module' => 'shift', 'action' => 'open', 'description' => 'Buka shift'],
            ['module' => 'shift', 'action' => 'close', 'description' => 'Tutup shift'],
            ['module' => 'shift', 'action' => 'read', 'description' => 'Lihat riwayat shift'],
            ['module' => 'attendance', 'action' => 'clock_in', 'description' => 'Clock in'],
            ['module' => 'attendance', 'action' => 'clock_out', 'description' => 'Clock out'],
            ['module' => 'attendance', 'action' => 'read', 'description' => 'Lihat absensi'],
            ['module' => 'attendance', 'action' => 'correct', 'description' => 'Koreksi absensi'],
            ['module' => 'employee', 'action' => 'read', 'description' => 'Lihat data karyawan'],
            ['module' => 'employee', 'action' => 'manage', 'description' => 'Tambah/edit/nonaktifkan karyawan'],
            ['module' => 'schedule', 'action' => 'manage', 'description' => 'Kelola jadwal shift'],
            ['module' => 'approval', 'action' => 'request', 'description' => 'Request approval'],
            ['module' => 'approval', 'action' => 'approve', 'description' => 'Approve transaksi'],
            ['module' => 'approval', 'action' => 'reject', 'description' => 'Tolak transaksi'],
            ['module' => 'approval', 'action' => 'rules_manage', 'description' => 'Kelola approval rules'],
            ['module' => 'report', 'action' => 'sales', 'description' => 'Laporan penjualan'],
            ['module' => 'report', 'action' => 'stock', 'description' => 'Laporan stok'],
            ['module' => 'report', 'action' => 'finance', 'description' => 'Laporan keuangan'],
            ['module' => 'report', 'action' => 'employee', 'description' => 'Laporan karyawan'],
            ['module' => 'report', 'action' => 'export', 'description' => 'Export laporan'],
            ['module' => 'outlet', 'action' => 'manage', 'description' => 'Kelola outlet & cabang'],
            ['module' => 'rbac', 'action' => 'manage', 'description' => 'Kelola role & permissions'],
            ['module' => 'payment_gateway', 'action' => 'manage', 'description' => 'Konfigurasi payment gateway'],
            ['module' => 'integration', 'action' => 'manage', 'description' => 'Konfigurasi GoFood/GrabFood'],
            ['module' => 'notification', 'action' => 'manage', 'description' => 'Setting notifikasi'],
            ['module' => 'printer', 'action' => 'manage', 'description' => 'Konfigurasi printer'],
        ];
    }

    public static function permissionNames(): array
    {
        return array_map(
            fn (array $permission) => $permission['module'] . ':' . $permission['action'],
            self::permissionCatalog(),
        );
    }

    public static function defaultsForRoleType(string $type): array
    {
        $matrix = [
            'kitchen' => [
                'auth:login',
                'auth:logout',
                'order:read',
                'order:update_status',
                'kitchen:read',
                'kitchen:update_status',
                'table:read',
                'attendance:clock_in',
                'attendance:clock_out',
                'approval:request',
            ],
            'bar' => [
                'auth:login',
                'auth:logout',
                'order:read',
                'order:update',
                'order:update_status',
                'order:approve_edit',
                'kitchen:read',
                'kitchen:approve',
                'table:read',
                'attendance:clock_in',
                'attendance:clock_out',
                'approval:request',
            ],
            'kasir' => [
                'auth:login',
                'auth:logout',
                'order:read',
                'order:create',
                'order:update',
                'order:cancel',
                'order:update_status',
                'order:approve_edit',
                'order:split_bill',
                'order:void',
                'payment:create',
                'payment:read',
                'payment:refund',
                'payment:void',
                'table:read',
                'table:qr_generate',
                'reservation:read',
                'reservation:create',
                'reservation:update',
                'reservation:cancel',
                'product:read',
                'customer:read',
                'customer:create',
                'customer:update',
                'membership:read',
                'membership:register',
                'loyalty:redeem',
                'kasbon:read',
                'kasbon:create',
                'kasbon:pay',
                'cicilan:manage',
                'po:read',
                'po:create',
                'po:pay',
                'po:cancel',
                'promo:read',
                'promo:apply',
                'shift:open',
                'shift:close',
                'shift:read',
                'attendance:clock_in',
                'attendance:clock_out',
                'approval:request',
            ],
            'supervisor' => [
                'auth:login',
                'auth:logout',
                'order:read',
                'order:create',
                'order:update',
                'order:cancel',
                'order:update_status',
                'order:approve_edit',
                'order:split_bill',
                'order:void',
                'payment:create',
                'payment:read',
                'payment:refund',
                'payment:void',
                'kitchen:read',
                'table:read',
                'table:manage',
                'table:qr_generate',
                'reservation:read',
                'reservation:create',
                'reservation:update',
                'reservation:cancel',
                'product:read',
                'product:update',
                'product:toggle_availability',
                'stock:read',
                'stock:add',
                'stock:adjust',
                'stock:write_off',
                'raw_material:read',
                'customer:read',
                'customer:create',
                'customer:update',
                'membership:read',
                'membership:register',
                'loyalty:redeem',
                'kasbon:read',
                'kasbon:create',
                'kasbon:pay',
                'kasbon:write_off',
                'cicilan:manage',
                'po:read',
                'po:create',
                'po:pay',
                'po:cancel',
                'promo:read',
                'promo:toggle',
                'promo:apply',
                'shift:open',
                'shift:close',
                'shift:read',
                'attendance:clock_in',
                'attendance:clock_out',
                'attendance:read',
                'attendance:correct',
                'employee:read',
                'schedule:manage',
                'approval:request',
                'approval:approve',
                'approval:reject',
                'report:sales',
                'report:stock',
                'report:employee',
                'report:export',
                'notification:manage',
                'printer:manage',
            ],
        ];

        if ($type === 'owner') {
            return self::permissionNames();
        }

        return $matrix[$type] ?? [];
    }
}
